// 漂移形状（第五十一轮 R51-H2）—— 一处实现，多个判据共用。
//
// 立它的理由是一手的：第四十九轮那次 README 非幂等，S7 只印出「脚本 → 产物路径」，
// 拿到名字仍然要人肉 diff 才知道多了个空行；`check-doc-commands --check` 的 D7 也只说「漂了」。
// 对照上游：`sqlalchemy/alembic` 的 `check` 抛 `AutogenerateDiffsDetected(f"...{diffs}", diffs=diffs)`
// —— 差集**原文**进异常消息且结构化可取；`psf/black --check --diff` 干脆把 diff 打成输出。
// 也就是说"红因可比"不是锦上添花，是漂移类判据能被接手的前提。
//
// 两个生成物（S7 的双跑、D7 的 README 逐字节）都从这里出，**禁止**在各自的 detail 里再算一遍
// —— 同一判断两处实现的话，改一份不会让另一份跟上（户内既有规：修一类不修一例 / 一处一判）。
import { createHash } from 'node:crypto'

export const SHA_PREFIX = 8

const sha8 = (buf) => createHash('sha256').update(buf).digest('hex').slice(0, SHA_PREFIX)

/** 按字节切行后找**第一处**不同的行号（1 起）；一侧缺席 ⇒ 1；完全等 ⇒ null。 */
export function firstDiffLine(before, after) {
  if (before === null || before === undefined) return after === null || after === undefined ? null : 1
  if (after === null || after === undefined) return 1
  const a = before.toString('utf8').split('\n')
  const b = after.toString('utf8').split('\n')
  const n = Math.min(a.length, b.length)
  for (let i = 0; i < n; i += 1) if (a[i] !== b[i]) return i + 1
  return a.length === b.length ? null : n + 1
}

/**
 * 一条漂移的最小可读形状。`kind` 让"缺席"与"内容变了"可分：
 * 旧形状里 `(新增)`/`(消失)` 混在 sha 字段里，格式化时会拼出 `→(新增)` 这种指不到行的东西。
 */
export function describeDrift(path, before, after) {
  const hasB = !(before === null || before === undefined)
  const hasA = !(after === null || after === undefined)
  return {
    path,
    kind: !hasB && !hasA ? 'both-absent' : (!hasB ? 'created' : (!hasA ? 'removed' : 'modified')),
    before_sha: hasB ? sha8(Buffer.isBuffer(before) ? before : Buffer.from(String(before))) : null,
    after_sha: hasA ? sha8(Buffer.isBuffer(after) ? after : Buffer.from(String(after))) : null,
    first_diff_line: firstDiffLine(hasB ? Buffer.from(String(before)) : null,
      hasA ? Buffer.from(String(after)) : null),
  }
}

/**
 * 判据输出用的单行格式：`产物#L7 a1b2c3d4→e5f6a7b8`。
 * 传进来的若不是本模块产出的结构体（裸字符串＝上一轮的旧形状），**点名成形状不合**，
 * 不静默兼容：兼容一次，就等于允许下一个调用方继续交裸串。
 */
export function formatDrift(d) {
  if (!d || typeof d !== 'object' || typeof d.path !== 'string') {
    return `[形状不合:期望 describeDrift() 的结构体，实得 ${JSON.stringify(d)?.slice(0, 40)}]`
  }
  const at = d.first_diff_line ? `#L${d.first_diff_line}` : ''
  const arrow = d.before_sha && d.after_sha ? `${d.before_sha}→${d.after_sha}`
    : (d.kind === 'created' ? `(新建)${d.after_sha}` : (d.kind === 'removed' ? `${d.before_sha}(消失)` : '(两侧都缺)'))
  return `${d.path}${at} ${arrow}`
}
